"""Models URL migration

Revision ID: 4a003f491630
Revises: 46143e5dc81b
Create Date: 2024-11-19 19:15:40.014505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a003f491630'
down_revision = '46143e5dc81b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hit_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.alter_column('classify_user',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.alter_column('classify_user',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.drop_column('hit_count')

    # ### end Alembic commands ###
