"""Models migration

Revision ID: e627ac7f2ba7
Revises: 6b3b246515c6
Create Date: 2024-11-18 22:50:09.647080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e627ac7f2ba7'
down_revision = '6b3b246515c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
